"""函数签名数据库 — (参数名列表, 返回值类型, 是否可变参)"""


SIGS = {
    "__assert_fail": (["assertion", "file", "line", "function"], "void", False),
    "abort": ([], "void", False),
    "abs": (["j"], "int", False),
    "accept": (["sockfd", "addr", "addrlen"], "int", False),
    "assert": (["expression"], "void", False),
    "atexit": (["function"], "int", False),
    "atoi": (["nptr"], "int", False),
    "atol": (["nptr"], "long", False),
    "atoll": (["nptr"], "long long", False),
    "bind": (["sockfd", "addr", "addrlen"], "int", False),
    "brk": (["addr"], "int", False),
    "bsearch": (["key", "base", "nmemb", "size", "compar"], "void*", False),
    "calloc": (["nmemb", "size"], "void*", False),
    "clock": ([], "clock_t", False),
    "close": (["fd"], "int", False),
    "connect": (["sockfd", "addr", "addrlen"], "int", False),
    "difftime": (["time1", "time0"], "double", False),
    "exit": (["status"], "void", False),
    "fclose": (["stream"], "int", False),
    "fcntl": (["fd", "cmd"], "int", True),
    "fflush": (["stream"], "int", False),
    "fgets": (["s", "size", "stream"], "char*", False),
    "fopen": (["pathname", "mode"], "FILE*", False),
    "fprintf": (["stream", "format"], "int", True),
    "fputs": (["s", "stream"], "int", False),
    "fread": (["ptr", "size", "nmemb", "stream"], "size_t", False),
    "free": (["ptr"], "void", False),
    "freeaddrinfo": (["res"], "void", False),
    "fscanf": (["stream", "format"], "int", True),
    "fseek": (["stream", "offset", "whence"], "int", False),
    "fstat": (["fd", "statbuf"], "int", False),
    "ftell": (["stream"], "long", False),
    "fwrite": (["ptr", "size", "nmemb", "stream"], "size_t", False),
    "getaddrinfo": (["node", "service", "hints", "res"], "int", False),
    "getenv": (["name"], "char*", False),
    "gethostbyname": (["name"], "struct hostent*", False),
    "gmtime": (["timep"], "struct tm*", False),
    "ioctl": (["fd", "request"], "int", True),
    "isalnum": (["c"], "int", False),
    "isalpha": (["c"], "int", False),
    "isdigit": (["c"], "int", False),
    "islower": (["c"], "int", False),
    "isspace": (["c"], "int", False),
    "isupper": (["c"], "int", False),
    "labs": (["j"], "long", False),
    "listen": (["sockfd", "backlog"], "int", False),
    "localeconv": ([], "struct lconv*", False),
    "localtime": (["timep"], "struct tm*", False),
    "longjmp": (["env", "val"], "void", False),
    "lseek": (["fd", "offset", "whence"], "off_t", False),
    "lstat": (["pathname", "statbuf"], "int", False),
    "malloc": (["size"], "void*", False),
    "memcmp": (["s1", "s2", "n"], "int", False),
    "memcpy": (["dst", "src", "n"], "void*", False),
    "memmove": (["dst", "src", "n"], "void*", False),
    "memset": (["s", "c", "n"], "void*", False),
    "mktime": (["tm"], "time_t", False),
    "mmap": (["addr", "length", "prot", "flags", "fd", "offset"], "void*", False),
    "munmap": (["addr", "length"], "int", False),
    "open": (["pathname", "flags", "mode"], "int", False),
    "perror": (["s"], "void", False),
    "poll": (["fds", "nfds", "timeout"], "int", False),
    "printf": (["format"], "int", True),
    "pthread_cond_signal": (["cond"], "int", False),
    "pthread_cond_wait": (["cond", "mutex"], "int", False),
    "pthread_create": (["thread", "attr", "start_routine", "arg"], "int", False),
    "pthread_join": (["thread", "retval"], "int", False),
    "pthread_mutex_lock": (["mutex"], "int", False),
    "pthread_mutex_unlock": (["mutex"], "int", False),
    "putchar": (["c"], "int", False),
    "puts": (["s"], "int", False),
    "qsort": (["base", "nmemb", "size", "compar"], "void", False),
    "raise": (["sig"], "int", False),
    "rand": ([], "int", False),
    "read": (["fd", "buf", "count"], "ssize_t", False),
    "realloc": (["ptr", "size"], "void*", False),
    "recv": (["sockfd", "buf", "len", "flags"], "ssize_t", False),
    "remove": (["pathname"], "int", False),
    "rename": (["oldpath", "newpath"], "int", False),
    "sbrk": (["increment"], "void*", False),
    "scanf": (["format"], "int", True),
    "select": (["nfds", "readfds", "writefds", "exceptfds", "timeout"], "int", False),
    "send": (["sockfd", "buf", "len", "flags"], "ssize_t", False),
    "setjmp": (["env"], "int", False),
    "setlocale": (["category", "locale"], "char*", False),
    "signal": (["signum", "handler"], "void (*)(int)", False),
    "snprintf": (["buf", "size", "format"], "int", True),
    "socket": (["domain", "type", "protocol"], "int", False),
    "sprintf": (["buf", "format"], "int", True),
    "srand": (["seed"], "void", False),
    "sscanf": (["buf", "format"], "int", True),
    "stat": (["pathname", "statbuf"], "int", False),
    "strcat": (["dst", "src"], "char*", False),
    "strchr": (["s", "c"], "char*", False),
    "strcmp": (["s1", "s2"], "int", False),
    "strcpy": (["dst", "src"], "char*", False),
    "strcspn": (["s", "reject"], "size_t", False),
    "strdup": (["s"], "char*", False),
    "strerror": (["errnum"], "char*", False),
    "strlen": (["s"], "size_t", False),
    "strncat": (["dst", "src", "n"], "char*", False),
    "strncmp": (["s1", "s2", "n"], "int", False),
    "strncpy": (["dst", "src", "n"], "char*", False),
    "strndup": (["s", "n"], "char*", False),
    "strpbrk": (["s", "accept"], "char*", False),
    "strrchr": (["s", "c"], "char*", False),
    "strspn": (["s", "accept"], "size_t", False),
    "strstr": (["haystack", "needle"], "char*", False),
    "strtod": (["nptr", "endptr"], "double", False),
    "strtof": (["nptr", "endptr"], "float", False),
    "strtok": (["s", "delim"], "char*", False),
    "strtol": (["nptr", "endptr", "base"], "long", False),
    "strtold": (["nptr", "endptr"], "long double", False),
    "strtoul": (["nptr", "endptr", "base"], "unsigned long", False),
    "system": (["command"], "int", False),
    "time": (["t"], "time_t", False),
    "tolower": (["c"], "int", False),
    "toupper": (["c"], "int", False),
    "write": (["fd", "buf", "count"], "ssize_t", False),
}


def get_sig_map():
    """返回 Rust SigDb.load() 兼容格式"""
    return SIGS
